

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    container_name: ode-backend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    container_name: ode-frontend
    depends_on:
      - backend
    # Конфигурация Nginx прямо в compose
    volumes:
      - ./frontend:/usr/share/nginx/html
    command: >
      sh -c "echo '
      server {
          listen 80;
          server_name localhost;
          
          location / {
              root /usr/share/nginx/html;
              index index.html;
              try_files $$uri $$uri/ /index.html;
          }
          
          location /api {
              proxy_pass http://backend:8080;
              proxy_set_header Host $$host;
          }
      }' > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"